SET(OptrisTestLoc "${USERPROFILE}/Documents/Optris/SDK")
IF(NOT EXISTS "${OptrisTestLoc}")
	SET(OptrisTestLoc "C:/Users/Public/Documents/Optris/SDK")
	IF(NOT EXISTS "${OptrisTestLoc}")
		OPTION(USE_OPTRIS "Build with Optris compatability" FALSE)
		SET(optris_FOUND FALSE)
	ELSE()
		OPTION(USE_OPTRIS "Build with Optris compatability" TRUE)
		SET(optris_FOUND TRUE)
	ENDIF()
ELSE()
	IF("${CMAKE_SIZEOF_VOID_P}" EQUAL "8")
		IF(USE_OPTRIS)
			MESSAGE(WARNING "The Windows Optris demo app compiles, but does not run in 64-bit mode. You have manually specified to include the Optris library (and demo app) in the project by selecting the USE_OPTRIS checkbox. It is advised to switch to 32-bit mode to use this functionality, however, if you get it to work in 64-bit mode, please let me know!")
		ELSE()
			MESSAGE(WARNING "The Windows Optris demo app compiles, but does not run in 64-bit mode. The Optris libraries will be excluded from the 64-bit build unless you manually select the USE_OPTRIS checkbox. It is advised to switch to 32-bit mode to use this functionality.")
		ENDIF()
		OPTION(USE_OPTRIS "Build with Optris compatability" FALSE)
	ELSE()
		OPTION(USE_OPTRIS "Build with Optris compatability" TRUE)
	ENDIF()
	SET(optris_FOUND TRUE)
ENDIF()
