IF(WIN32 OR win64)
   SET(IS_WINDOWS TRUE)
   SET(IS_LINUX FALSE)
   ADD_DEFINITIONS(-D_IS_WINDOWS_)
   SET(DLL_EXT "dll")
   SET(LIB_PREFIX "")
   string(REGEX REPLACE "\\\\" "/" USERPROFILE "$ENV{USERPROFILE}")

ELSE()
   SET(IS_WINDOWS FALSE)
   SET(IS_LINUX TRUE)
   ADD_DEFINITIONS(-D_IS_LINUX_)
   SET(DLL_EXT "so")
   SET(LIB_PREFIX "lib")
   string(REGEX REPLACE "\\\\" "/" USERPROFILE "$ENV{HOME}")
   SET(THERMALVIS_COMPILE_FLAGS "${THERMALVIS_COMPILE_FLAGS} -Wno-write-strings")
ENDIF()

add_definitions( -D_USERPROFILE_=\"${USERPROFILE}\" )


