SET(OptrisTestLoc "${USERPROFILE}/Documents/Optris/SDK")
IF(NOT EXISTS "${OptrisTestLoc}")
	SET(OptrisTestLoc "C:/Users/Public/Documents/Optris/SDK")
	IF(NOT EXISTS "${OptrisTestLoc}")
		OPTION(USE_OPTRIS "Build with Optris compatability" FALSE)
		SET(optris_FOUND FALSE)
	ELSE()
		OPTION(USE_OPTRIS "Build with Optris compatability" TRUE)
		SET(optris_FOUND TRUE)
	ENDIF()
ELSE()
	OPTION(USE_OPTRIS "Build with Optris compatability" TRUE)
	SET(optris_FOUND TRUE)
ENDIF()
