find_package(PCL QUIET)
IF(PCL_FOUND)
	IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
		STRING( FIND ${PCL_COMMON_LIBRARY} "32" APOSITION )
		IF (NOT "${APOSITION}" STREQUAL "-1")
			OPTION(USE_PCL "Build PCL-dependent functions." FALSE)
			MESSAGE(WARNING "This is a 64-bit build, and it looks like CMake actually found the 32-bit PCL libraries to link to! Therefore PCL has been excluded from the build.")
		ELSE()
			OPTION(USE_PCL "Build PCL-dependent functions." TRUE)
		ENDIF()
	ELSE()
		STRING( FIND ${PCL_COMMON_LIBRARY} "64" APOSITION ) 
		IF (NOT "${APOSITION}" STREQUAL "-1")
			OPTION(USE_PCL "Build PCL-dependent functions." FALSE)
			MESSAGE(WARNING "This is a 32-bit build, and it looks like CMake actually found the 64-bit PCL libraries to link to! Therefore PCL has been excluded from the build.")
		ELSE()
			OPTION(USE_PCL "Build PCL-dependent functions." TRUE)
		ENDIF()
	ENDIF()
ELSE()
	OPTION(USE_PCL "Build PCL-dependent functions." FALSE)
ENDIF()

IF(USE_PCL)
	FIND_PACKAGE( PCL COMPONENTS common io )
	IF(PCL_FOUND)
		MESSAGE(STATUS "PCL Found!")
		ADD_DEFINITIONS( -D_USE_PCL_ )
		INCLUDE_DIRECTORIES(${PCL_INCLUDE_DIRS})
		SET(ADDITIONAL_LIBRARIES ${ADDITIONAL_LIBRARIES} ${PCL_LIBRARIES})
	ELSE()
		MESSAGE(FATAL_ERROR "PCL not found! Much of the libraries can be built without PCL, however, so consider opting not to use it.")
	ENDIF()
	IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
		STRING( FIND ${PCL_COMMON_LIBRARY} "32" APOSITION )
		IF (NOT "${APOSITION}" STREQUAL "-1")
			MESSAGE(WARNING "This is a 64-bit build, and it looks like CMake actually found the 32-bit PCL libraries to link to! This may cause compilation problems..")
		ENDIF()
	ELSE()
		STRING( FIND ${PCL_COMMON_LIBRARY} "64" APOSITION ) 
		IF (NOT "${APOSITION}" STREQUAL "-1")
			MESSAGE(WARNING "This is a 32-bit build, and it looks like CMake actually found the 64-bit PCL libraries to link to! This may cause compilation problems..")
		ENDIF()
	ENDIF()
ENDIF()

IF(OPENNI_LIBRARY)
	STRING( FIND ${OPENNI_LIBRARY} ".dll" APOSITION )
	IF (NOT "${APOSITION}" STREQUAL "-1")
		string(REGEX REPLACE ".dll" ".lib" FIXED_OPENNI_LIBRARY "${OPENNI_LIBRARY}")
		string(REGEX REPLACE "Bin" "Lib" FIXED_OPENNI_LIBRARY "${FIXED_OPENNI_LIBRARY}")
		SET(OPENNI_LIBRARY "${FIXED_OPENNI_LIBRARY}" CACHE STRING "OpenNI 1.X Library. If no cached value is provided, it will often incorrectly default to a DLL." FORCE)
	ELSE()
		SET(OPENNI_LIBRARY "C:/Program Files/OpenNI/Lib64/openNI64.lib" CACHE STRING "OpenNI 1.X Library. If no cached value is provided, it will often incorrectly default to a DLL.")
	endif()
ENDIF()

IF(OPENNI2_LIBRARY)
	STRING( FIND ${OPENNI2_LIBRARY} ".dll" APOSITION )
	IF (NOT "${APOSITION}" STREQUAL "-1")
		string(REGEX REPLACE ".dll" ".lib" FIXED_OPENNI2_LIBRARY "${OPENNI2_LIBRARY}")
		string(REGEX REPLACE "Tools" "Lib" FIXED_OPENNI2_LIBRARY "${FIXED_OPENNI2_LIBRARY}")
		SET(OPENNI2_LIBRARY "${FIXED_OPENNI2_LIBRARY}" CACHE STRING "OpenNI 2.X Library. If no cached value is provided, it will often incorrectly default to a DLL." FORCE)
	ELSE()
		SET(OPENNI2_LIBRARY "C:/Program Files/OpenNI2/Lib/OpenNI2.lib" CACHE STRING "OpenNI 2.X Library. If no cached value is provided, it will often incorrectly default to a DLL.")
	endif()
ENDIF()