SET(OptrisTestLoc "${USERPROFILE}/Documents/Optris/SDK")
IF(NOT EXISTS "${OptrisTestLoc}")
	SET(OptrisTestLoc "C:/Users/Public/Documents/Optris/SDK")
	IF(NOT EXISTS "${OptrisTestLoc}")
		OPTION(USE_OPTRIS_SDK "Build with Optris compatability" FALSE)
	ELSE()
		OPTION(USE_OPTRIS_SDK "Build with Optris compatability" TRUE)
	ENDIF()
ELSE()
	OPTION(USE_OPTRIS_SDK "Build with Optris compatability" TRUE)
ENDIF()
