FIND_PACKAGE( OpenCV HINTS "/usr/local/share/OpenCV" "${USERPROFILE}/Documents/opencv/build" "C:/Users/Public/Documents/opencv/build" "${USERPROFILE}/Documents/Code/BUILDS/opencv/build" "${USERPROFILE}/Documents/GitHub/BUILDS/OpenCV")
STRING(REGEX REPLACE "/Release/Release" "/Release" OpenCV_LIB_DIR_OPT "${OpenCV_LIB_DIR_OPT}")
STRING(REGEX REPLACE "/Debug/Debug" "/Debug" OpenCV_LIB_DIR_DBG "${OpenCV_LIB_DIR_DBG}")

IF(OpenCV_FOUND AND ("${OpenCV_DIR}" STREQUAL "${OpenCV_CONFIG_PATH}") AND (NOT("${OpenCV_LIB_DIR_DBG}" STREQUAL "/Debug")) AND (NOT("${OpenCV_LIB_DIR_OPT}" STREQUAL "/Release")) )
	MESSAGE(STATUS "OpenCV Found!")
	
	if ("${OpenCV_LIB_DIR_OPT}" STREQUAL "")
		IF (NOT IS_WINDOWS)
			SET(OpenCV_LIB_DIR_OPT "/usr/local/lib")
			SET(OpenCV_LIB_DIR_DBG "/usr/local/lib")
			SET(OpenCV_BIN_DIR_OPT "/usr/local/lib")
			SET(OpenCV_BIN_DIR_DBG "/usr/local/lib")
		ELSE()
			MESSAGE(FATAL_ERROR "OpenCV_LIB_DIR_OPT is empty!")
		ENDIF()
	else()
		STRING(REGEX REPLACE "/lib" "/bin" OpenCV_BIN_DIR_OPT "${OpenCV_LIB_DIR_OPT}")
		STRING(REGEX REPLACE "/lib" "/bin" OpenCV_BIN_DIR_DBG "${OpenCV_LIB_DIR_DBG}")
	endif()
	
ELSEIF(EXISTS "${OpenCV_DIR}/")
	MESSAGE(WARNING "OpenCV not entirely found, but directory address <OpenCV_DIR> located and so assuming local build at ${OpenCV_DIR}")
	IF( (NOT EXISTS "${OpenCV_DIR}/lib/Debug/") AND (NOT EXISTS "${OpenCV_DIR}/lib/Release/") )
		MESSAGE(FATAL_ERROR "Provided path for OpenCV does not appear to contain valid debug OR release libraries!")
	ENDIF()
	
	SET(OpenCV_LIB_DIR_OPT "${OpenCV_DIR}/lib/Release" CACHE STRING "..." FORCE)
	SET(OpenCV_LIB_DIR_DBG "${OpenCV_DIR}/lib/Debug" CACHE STRING "..." FORCE)
	SET(OpenCV_3RDPARTY_LIB_DIR_OPT "${OpenCV_DIR}/lib/Release" CACHE STRING "..." FORCE)
	SET(OpenCV_3RDPARTY_LIB_DIR_DBG "${OpenCV_DIR}/lib/Debug" CACHE STRING "..." FORCE)
	
	SET(OPENCV_FOUND TRUE CACHE BOOL "..." FORCE)
	SET(OpenCV_FOUND TRUE CACHE BOOL "..." FORCE)
	
	SET(OpenCV_BIN_DIR_OPT "${OpenCV_DIR}/bin/Release")
	SET(OpenCV_BIN_DIR_DBG "${OpenCV_DIR}/bin/Debug")
	SET(OpenCV_CONFIG_PATH "${OpenCV_DIR}" CACHE STRING "..." FORCE)
ELSE()
	MESSAGE(FATAL_ERROR "OpenCV not found! Please set the <OpenCV_DIR> variable to the OpenCV build directory.")
ENDIF()

IF(OpenCV_FOUND)
	INCLUDE_DIRECTORIES(${OpenCV_INCLUDE_DIRS})
	LIST(APPEND ADDITIONAL_LIBRARIES ${OpenCV_LIBS})
	IF (IS_WINDOWS)
		STRING(REGEX REPLACE "\\." "" OPENCV_VER "${OpenCV_VERSION}")
	ELSE()
		SET(OPENCV_VER "")
	ENDIF()
	IF(OpenCV_VERSION_MAJOR GREATER 2)
		MESSAGE(STATUS "OpenCV Version is 3+, so some functions differ. This should be handled by compiler directives.")
		ADD_DEFINITIONS( -D_OPENCV_VERSION_3_PLUS_ )
	ENDIF()
	IF (OPENCV_GPU_FOUND)
		MESSAGE(STATUS "OpenCV GPU module found, so including it.")
		ADD_DEFINITIONS( -D_USE_OPENCV_GPU_ )
	ENDIF()
ENDIF()
